language: ruby
sudo: required
install: true
script:
  - curl icanhazip.com
env:
  matrix:
    - JOB=1
    - JOB=2
    - JOB=3
    - JOB=4
    - JOB=1
    - JOB=2
    - JOB=3
    - JOB=4
    - JOB=1
    - JOB=2
    - JOB=3
    - JOB=4
    - JOB=1
    - JOB=2
    - JOB=3
    - JOB=4
