language: ruby
services:
    - docker
sudo: required
install: true
script:
    - ruby -e 'sleep(9 + rand * 60)'
env:
  matrix:
    - JOB=1
    - JOB=2
    - JOB=3
    - JOB=4
    - JOB=5
    - JOB=6
    - JOB=7
    - JOB=8
    - JOB=9
    - JOB=10
    - JOB=11
    - JOB=12
